//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_Partidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAR_Partidas()
        {
            this.USP_UsuariosPartidas = new HashSet<USP_UsuariosPartidas>();
        }
    
        public int PAR_Id { get; set; }
        public System.DateTime PAR_FechaHora { get; set; }
        public bool PAR_Cerrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USP_UsuariosPartidas> USP_UsuariosPartidas { get; set; }
    }
}
