//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REP_RespuestasPreguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REP_RespuestasPreguntas()
        {
            this.REU_RespuestasUsuarios = new HashSet<REU_RespuestasUsuarios>();
        }
    
        public int REP_Id { get; set; }
        public int PRE_Id { get; set; }
        public int RES_Id { get; set; }
        public bool REP_Correcta { get; set; }
    
        public virtual PRE_Preguntas PRE_Preguntas { get; set; }
        public virtual RES_Respuestas RES_Respuestas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REU_RespuestasUsuarios> REU_RespuestasUsuarios { get; set; }
    }
}
