//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class REU_RespuestasUsuarios
    {
        public int REU_Id { get; set; }
        public int REP_Id { get; set; }
        public int USU_Id { get; set; }
    
        public virtual REP_RespuestasPreguntas REP_RespuestasPreguntas { get; set; }
        public virtual USU_Usuarios USU_Usuarios { get; set; }
    }
}
