//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USP_UsuariosPartidas
    {
        public int USP_Id { get; set; }
        public int PAR_Id { get; set; }
        public int USU_Id { get; set; }
        public int USP_MarcadorFinal { get; set; }
    
        public virtual PAR_Partidas PAR_Partidas { get; set; }
        public virtual USU_Usuarios USU_Usuarios { get; set; }
    }
}
